
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Sep 24 2024 19:40:53 UTC (Sep 24 2024 19:40:53 UTC)

// Verification Directory fv/LZ32 

module LZ32(bus, LZ);
  input [31:0] bus;
  output [4:0] LZ;
  wire [31:0] bus;
  wire [4:0] LZ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_46, n_47, n_48;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_65;
  sky130_fd_sc_hd__o22ai_1 g2240__2398(.A1 (bus[25]), .A2 (n_65), .B1
       (bus[31]), .B2 (n_52), .Y (LZ[0]));
  sky130_fd_sc_hd__or4_1 g2242__5107(.A (bus[27]), .B (bus[31]), .C
       (bus[29]), .D (n_63), .X (n_65));
  sky130_fd_sc_hd__o31a_1 g2238__6260(.A1 (bus[28]), .A2 (bus[29]), .A3
       (n_62), .B1 (n_9), .X (LZ[1]));
  sky130_fd_sc_hd__o21ai_0 g2244__4319(.A1 (bus[16]), .A2 (n_61), .B1
       (n_36), .Y (n_63));
  sky130_fd_sc_hd__nor3_1 g2239__8428(.A (bus[26]), .B (bus[27]), .C
       (n_59), .Y (n_62));
  sky130_fd_sc_hd__nor2_1 g2246__5526(.A (bus[15]), .B (n_60), .Y
       (n_61));
  sky130_fd_sc_hd__nor2_1 g2247__6783(.A (bus[14]), .B (n_58), .Y
       (n_60));
  sky130_fd_sc_hd__nor3_1 g2241__3680(.A (bus[24]), .B (bus[25]), .C
       (n_57), .Y (n_59));
  sky130_fd_sc_hd__nor2_1 g2249__1617(.A (bus[13]), .B (n_56), .Y
       (n_58));
  sky130_fd_sc_hd__nor3_1 g2243__2802(.A (bus[23]), .B (bus[22]), .C
       (n_54), .Y (n_57));
  sky130_fd_sc_hd__nor2_1 g2251__1705(.A (bus[12]), .B (n_55), .Y
       (n_56));
  sky130_fd_sc_hd__nor2_1 g2254__5122(.A (bus[11]), .B (n_53), .Y
       (n_55));
  sky130_fd_sc_hd__nor3_1 g2245__8246(.A (bus[21]), .B (bus[20]), .C
       (n_51), .Y (n_54));
  sky130_fd_sc_hd__nor2_1 g2259__7098(.A (bus[10]), .B (n_46), .Y
       (n_53));
  sky130_fd_sc_hd__nor2_1 g2255__6131(.A (bus[30]), .B (n_47), .Y
       (n_52));
  sky130_fd_sc_hd__a211oi_1 g2248__1881(.A1 (n_40), .A2 (n_26), .B1
       (bus[19]), .C1 (bus[18]), .Y (n_51));
  sky130_fd_sc_hd__nor2_1 g2253__5115(.A (n_48), .B (n_44), .Y (LZ[3]));
  sky130_fd_sc_hd__a21oi_1 g2250__7482(.A1 (n_39), .A2 (n_43), .B1
       (n_48), .Y (LZ[2]));
  sky130_fd_sc_hd__nor2_1 g2260__4733(.A (bus[29]), .B (n_42), .Y
       (n_47));
  sky130_fd_sc_hd__nor2_1 g2261__6161(.A (bus[9]), .B (n_41), .Y
       (n_46));
  sky130_fd_sc_hd__nor4_1 g2252__9315(.A (bus[16]), .B (bus[18]), .C
       (n_48), .D (n_37), .Y (LZ[4]));
  sky130_fd_sc_hd__o31ai_1 g2257__9945(.A1 (bus[18]), .A2 (bus[16]),
       .A3 (n_31), .B1 (n_43), .Y (n_44));
  sky130_fd_sc_hd__nor2_1 g2262__2883(.A (bus[28]), .B (n_34), .Y
       (n_42));
  sky130_fd_sc_hd__nor2_1 g2264__2346(.A (bus[8]), .B (n_38), .Y
       (n_41));
  sky130_fd_sc_hd__o31ai_1 g2256__1666(.A1 (bus[12]), .A2 (bus[13]),
       .A3 (n_30), .B1 (n_10), .Y (n_40));
  sky130_fd_sc_hd__o311ai_0 g2258__7410(.A1 (bus[19]), .A2 (bus[18]),
       .A3 (n_28), .B1 (n_35), .C1 (n_19), .Y (n_39));
  sky130_fd_sc_hd__nor2_1 g2269__6417(.A (bus[7]), .B (n_32), .Y
       (n_38));
  sky130_fd_sc_hd__nand4_1 g2263__5477(.A (n_29), .B (n_36), .C (n_43),
       .D (n_35), .Y (n_37));
  sky130_fd_sc_hd__nor2_1 g2265__2398(.A (bus[27]), .B (n_33), .Y
       (n_34));
  sky130_fd_sc_hd__nor2_1 g2270__5107(.A (bus[26]), .B (n_25), .Y
       (n_33));
  sky130_fd_sc_hd__nor2_1 g2272__6260(.A (bus[6]), .B (n_22), .Y
       (n_32));
  sky130_fd_sc_hd__nand3_1 g2266__4319(.A (n_24), .B (n_36), .C (n_35),
       .Y (n_31));
  sky130_fd_sc_hd__o31a_1 g2267__8428(.A1 (bus[9]), .A2 (bus[8]), .A3
       (n_21), .B1 (n_8), .X (n_30));
  sky130_fd_sc_hd__nand3b_1 g2274__5526(.A_N (n_27), .B (n_18), .C
       (n_23), .Y (n_29));
  sky130_fd_sc_hd__o21ai_0 g2268__6783(.A1 (n_27), .A2 (n_15), .B1
       (n_26), .Y (n_28));
  sky130_fd_sc_hd__nor2_1 g2271__3680(.A (bus[25]), .B (n_20), .Y
       (n_25));
  sky130_fd_sc_hd__nand3b_1 g2273__1617(.A_N (n_27), .B (n_17), .C
       (n_23), .Y (n_24));
  sky130_fd_sc_hd__nor2_1 g2275__2802(.A (bus[5]), .B (n_16), .Y
       (n_22));
  sky130_fd_sc_hd__o31a_1 g2277__1705(.A1 (bus[4]), .A2 (bus[5]), .A3
       (n_7), .B1 (n_11), .X (n_21));
  sky130_fd_sc_hd__a221oi_1 g2278__5122(.A1 (n_1), .A2 (bus[22]), .B1
       (n_3), .B2 (n_19), .C1 (bus[24]), .Y (n_20));
  sky130_fd_sc_hd__inv_1 g2279(.A (n_17), .Y (n_18));
  sky130_fd_sc_hd__nor2_1 g2281__8246(.A (bus[4]), .B (n_12), .Y
       (n_16));
  sky130_fd_sc_hd__a21boi_0 g2276__7098(.A1 (n_13), .A2 (n_14), .B1_N
       (n_23), .Y (n_15));
  sky130_fd_sc_hd__nand2b_1 g2280__6131(.A_N (n_14), .B (n_13), .Y
       (n_17));
  sky130_fd_sc_hd__nor2_1 g2282__1881(.A (bus[3]), .B (n_4), .Y (n_12));
  sky130_fd_sc_hd__nor3b_1 g2283__5115(.A (bus[4]), .B (bus[5]), .C_N
       (n_11), .Y (n_13));
  sky130_fd_sc_hd__or3b_2 g2284__7482(.A (bus[12]), .B (bus[13]), .C_N
       (n_10), .X (n_27));
  sky130_fd_sc_hd__nor3b_1 g2285__4733(.A (bus[17]), .B (bus[19]), .C_N
       (n_19), .Y (n_36));
  sky130_fd_sc_hd__or3b_2 g2286__6161(.A (bus[28]), .B (bus[29]), .C_N
       (n_9), .X (n_48));
  sky130_fd_sc_hd__nor3b_1 g2288__9315(.A (bus[8]), .B (bus[9]), .C_N
       (n_8), .Y (n_23));
  sky130_fd_sc_hd__nor2b_1 g2289__9945(.A (n_5), .B_N (n_6), .Y (n_7));
  sky130_fd_sc_hd__nand2_1 g2290__2883(.A (n_6), .B (n_5), .Y (n_14));
  sky130_fd_sc_hd__a21oi_1 g2291__2346(.A1 (n_2), .A2 (bus[0]), .B1
       (bus[2]), .Y (n_4));
  sky130_fd_sc_hd__o21bai_1 g2292__1666(.A1 (bus[19]), .A2 (n_0), .B1_N
       (bus[20]), .Y (n_3));
  sky130_fd_sc_hd__nor4_1 g2287__7410(.A (bus[24]), .B (bus[26]), .C
       (bus[27]), .D (bus[25]), .Y (n_43));
  sky130_fd_sc_hd__nor2_1 g2298__6417(.A (bus[16]), .B (bus[17]), .Y
       (n_26));
  sky130_fd_sc_hd__nor2_1 g2301__5477(.A (bus[6]), .B (bus[7]), .Y
       (n_11));
  sky130_fd_sc_hd__nor2_1 g2300__2398(.A (bus[0]), .B (bus[1]), .Y
       (n_5));
  sky130_fd_sc_hd__nor2_1 g2293__5107(.A (bus[10]), .B (bus[11]), .Y
       (n_8));
  sky130_fd_sc_hd__nor2_1 g2294__6260(.A (bus[2]), .B (bus[3]), .Y
       (n_6));
  sky130_fd_sc_hd__nor2_1 g2297__4319(.A (bus[14]), .B (bus[15]), .Y
       (n_10));
  sky130_fd_sc_hd__nor2_1 g2299__8428(.A (bus[30]), .B (bus[31]), .Y
       (n_9));
  sky130_fd_sc_hd__nor2_1 g2295__5526(.A (bus[21]), .B (bus[23]), .Y
       (n_19));
  sky130_fd_sc_hd__nor2_1 g2296__6783(.A (bus[20]), .B (bus[22]), .Y
       (n_35));
  sky130_fd_sc_hd__inv_1 g2303(.A (bus[1]), .Y (n_2));
  sky130_fd_sc_hd__inv_1 g2304(.A (bus[23]), .Y (n_1));
  sky130_fd_sc_hd__inv_1 g2302(.A (bus[18]), .Y (n_0));
endmodule

