
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Sep 24 2024 19:43:46 UTC (Sep 24 2024 19:43:46 UTC)

// Verification Directory fv/lzc_32 

module lzc_32(a, c, v);
  input [31:0] a;
  output [4:0] c;
  output v;
  wire [31:0] a;
  wire [4:0] c;
  wire v;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14;
  sky130_fd_sc_hd__o221ai_1 g455__2398(.A1 (n_11), .A2 (c[4]), .B1
       (n_12), .B2 (n_13), .C1 (n_9), .Y (c[2]));
  sky130_fd_sc_hd__nand4b_1 g457__5107(.A_N (c[4]), .B (n_14), .C
       (n_10), .D (n_4), .Y (v));
  sky130_fd_sc_hd__o21bai_1 g456__6260(.A1 (n_14), .A2 (c[4]), .B1_N
       (n_13), .Y (c[3]));
  sky130_fd_sc_hd__nand3b_1 g458__4319(.A_N (n_13), .B (n_12), .C
       (n_2), .Y (c[4]));
  sky130_fd_sc_hd__o21a_1 g459__8428(.A1 (n_10), .A2 (n_8), .B1 (n_7),
       .X (n_11));
  sky130_fd_sc_hd__nand2_1 g460__5526(.A (n_9), .B (n_1), .Y (n_13));
  sky130_fd_sc_hd__inv_1 g461(.A (n_8), .Y (n_14));
  sky130_fd_sc_hd__nand2_1 g462__6783(.A (n_7), .B (n_3), .Y (n_8));
  sky130_fd_sc_hd__nor3b_1 g463__3680(.A (a[29]), .B (a[28]), .C_N
       (c[1]), .Y (n_9));
  sky130_fd_sc_hd__a21oi_1 g465__1617(.A1 (n_0), .A2 (a[29]), .B1
       (a[31]), .Y (c[0]));
  sky130_fd_sc_hd__nor4_1 g464__2802(.A (a[0]), .B (a[2]), .C (a[3]),
       .D (a[1]), .Y (n_4));
  sky130_fd_sc_hd__nor4_1 g471__1705(.A (a[4]), .B (a[6]), .C (a[7]),
       .D (a[5]), .Y (n_10));
  sky130_fd_sc_hd__nor4_1 g470__5122(.A (a[20]), .B (a[22]), .C
       (a[23]), .D (a[21]), .Y (n_12));
  sky130_fd_sc_hd__nor4_1 g468__8246(.A (a[8]), .B (a[10]), .C (a[11]),
       .D (a[9]), .Y (n_3));
  sky130_fd_sc_hd__nor4_1 g469__7098(.A (a[16]), .B (a[18]), .C
       (a[19]), .D (a[17]), .Y (n_2));
  sky130_fd_sc_hd__nor4_1 g466__6131(.A (a[24]), .B (a[26]), .C
       (a[27]), .D (a[25]), .Y (n_1));
  sky130_fd_sc_hd__nor4_1 g467__1881(.A (a[12]), .B (a[14]), .C
       (a[15]), .D (a[13]), .Y (n_7));
  sky130_fd_sc_hd__nor2_1 g472__5115(.A (a[30]), .B (a[31]), .Y (c[1]));
  sky130_fd_sc_hd__inv_1 g473(.A (a[30]), .Y (n_0));
endmodule

